[package]
name = "rsa-aes"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
libm = "0.2.11"
num = "0.4.3"
num-bigint = { version = "0.4", features = ["rand"] }
rand = "0.8"
rand_chacha = "0.9.0"
